create table if not exists percon
(
    id   int primary key generated by default as identity,
    name varchar(50) not null,
    age  int         not null

);
insert into percon(name, age)
VALUES ('Tom', 22);
insert into percon(name, age)
VALUES ('Cat', 23);
insert into percon(name, age)
VALUES ('Bil', 24);

create table if not exists bankcard
(
    id   int primary key generated by default as identity,
    name varchar(50) not null,
    person_id  int          references percon (id) on delete set null

);

insert into bankcard(name, person_id) VALUES ('Alfa',1);
insert into bankcard(name, person_id) VALUES ('Ros',2);
insert into bankcard(name, person_id) VALUES ('Cber',3);
insert into bankcard(name, person_id) VALUES ('Sofcom',1);
insert into bankcard(name, person_id) VALUES ('Amega',2);